config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tracked_domains do
    resources :events
  end
  
  resources :verifications, only: [:update]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:create, :index]
      match 'events.json' => "events#create", via: :options, as: :events_options
    end
  end

  #options 'api/v1/events.json' => "api/v1/events#index"
  match 'api/v1/events.json' => "api/v1/events#index", via: :options
  get 'get_started' => 'welcome#get_started', path: 'get_started'

  root 'welcome#index' 

end

app/models/tracked_domain.rb
class TrackedDomain < ActiveRecord::Base

  belongs_to :user
  has_many :events

  before_create :set_verfication_code

  scope :recent, lambda { order("tracked_domains.updated_at DESC, tracked_domains.created_at DESC") }
  scope :verified, -> {where(verified: true)}
  
  def check_verification
    doc = Nokogiri::HTML(HTTParty.get(self.url))
    vercode = doc.xpath("//meta[@name='verification_code']").first["content"]
    if vercode == self.verification_code
      self.verified = true
      return self.save
    else
      return false
    end
  end

  protected

  def set_verfication_code
    self.verification_code = SecureRandom.hex(30)
  end

end

app/controllers/tracked_domains_controller.rb
class TrackedDomainsController < ApplicationController 

  before_filter :authenticate_user!
  
  def index
    @tracked_domains = TrackedDomain.recent
  end

  def show
    @tracked_domain = TrackedDomain.find(params[:id])
  end

  def new
    @tracked_domain = TrackedDomain.new
  end

  def create
    @tracked_domain = TrackedDomain.new(td_params)
    @tracked_domain.user = current_user
    if @tracked_domain.save
      flash[:notice] = "Tracked Domain created uccessfully."
      redirect_to @tracked_domain
    else
      render :new  
    end  
  end

  def edit
    @tracked_domain = TrackedDomain.find(params[:id])
  end

  def update
    @tracked_domain = TrackedDomain.find(params[:id])
    if @tracked_domain.update_attributes(td_params)
      flash[:notice] = "Tracked Domain #{@tracked_domain.name} updated successfully."
      redirect_to @tracked_domain
    else
      render :edit
    end   
  end

  def delete
    @tracked_domain = TrackedDomain.find(params[:id])
  end

  def destroy
    @tracked_domain = TrackedDomain.find(params[:id])
    if @tracked_domain.destroy
    flash[:notice] = "Tracked Domain deleted successfully."
    else
     flash[:error] = "There was an error deleting the tracked_domain."
    end
    redirect_to tracked_domains_path
  end

  private

  def td_params
    params.require(:tracked_domain).permit(:user_id, :name, :description, :url, :verification_code, :verified) 
  end
end

app/helpers/tracked_domain_helper.rb
module TrackedDomainHelper
end

app/views/tracked_domains/_form.html.haml
= form_for @tracked_domain, class: 'form-horizontal', remote: true  do |f|
  .form-group
  = f.label :name
  = f.text_field :name, class: 'form-control'
  .form-group
  = f.label :description
  = f.text_field :description, class: 'form-control'
  .form-group
  = f.label :url
  = f.url_field :url, class: 'form-control'
  .form-group
  =f.submit "Save", class: 'btn btn-success btn-sm'

app/views/tracked_domains/delete.html.haml
%h1 TrackedDomain#delete
%p Find me in app/views/tracked_domain/delete.html.haml

app/views/tracked_domains/edit.html.haml
%h3 Edit Tracked Domain
.row
  .col-md-4
    .col-md-8
= render partial: 'form', locals: { tracked_domain: @tracked_domain} 
%br
= link_to "Back to #{@tracked_domain.name}", tracked_domain_path(@tracked_domain), class: 'btn btn-default btn-sm'

app/views/tracked_domains/index.html.haml
- @page_title = "Tracked Domains"
.container
  %h1 Tracked Domains

  %div
    = pluralize(@tracked_domains.size, 'tracked domain')
    found
  %br
  %table.table.table-condensed.table-hover
    %tr
      %th Name
      %th Description
      %th URL
      %th Verification Code
      %th Verified
      %th Actions
      - @tracked_domains.each do |tracked_domain|
        %tr
          %td= tracked_domain.name
          %td= tracked_domain.description
          %td= tracked_domain.url
          %td= tracked_domain.verification_code
          %td= tracked_domain.verified?
          %td  |
            = link_to 'Show', tracked_domain_path(tracked_domain.id)
            = link_to 'Edit', edit_tracked_domain_path(tracked_domain.id)
            = link_to 'Delete', tracked_domain_path(tracked_domain.id), method: :delete, data: { confirm: 'Are you sure you want to delete this tracked domain?' }
    
  = link_to "Add New Tracked Domain", new_tracked_domain_path, class: 'btn btn-default' 

app/views/tracked_domains/new.html.haml
%h3 Add a Tracked Domain
.row
  .col-md-4
    .col-md-8
= render partial: 'form', locals: { tracked_domain: @tracked_domain} 

app/views/tracked_domains/show.html.haml
.container
  %h3.col.md-6= @tracked_domain.name
  %p= @tracked_domain.description
  %p= @tracked_domain.url
  %p= @tracked_domain.verification_code

  %br

  - if @tracked_domain.verified == false
    = link_to "Check Verification", verification_path(@tracked_domain), method: :put
  - else 
    = link_to "View Events", tracked_domain_events_path(@tracked_domain), class: 'btn btn-default btn-sm'
  = link_to "Edit ", edit_tracked_domain_path(@tracked_domain), class: 'btn btn-success btn-sm'
  = link_to "Delete ", @tracked_domain, method: :delete, class: 'btn btn-danger btn-sm', data: {confirm: 'Are you sure you want to delete this tracked_domain?'}


  %hr
  -if @tracked_domain.verified?
    .badge.badge-info
      This is a verified tracked domain.

        