config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tracked_domains do
    resources :events
  end
  
  resources :verifications, only: [:update]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:create, :index]
      match 'events.json' => "events#create", via: :options, as: :events_options
    end
  end

  #options 'api/v1/events.json' => "api/v1/events#index"
  match 'api/v1/events.json' => "api/v1/events#index", via: :options
  get 'get_started' => 'welcome#get_started', path: 'get_started'

  root 'welcome#index' 

end

app/models/event.rb
class Event < ActiveRecord::Base

  belongs_to :tracked_domain

  scope :recent, lambda { order("events.updated_at DESC, events.created_at DESC") }
 
 
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < Api::V1::BaseController

  def create
    @tracked_domain = current_user.tracked_domain_from_url(request.referer)
    if @tracked_domain.blank?
      render nothing: true, status: :forbidden
    else
      @event = @tracked_domain.events.build(params[:event_params])
      if @event.save
        respond_with @event, location: api_v1_event_path(@event)
      else
        render json: {:error => "Invalid event"}, status: :unprocessable_entity 
      end
    end
  end

  def index
    render nothing: true, status: :ok
    @events = Event.all
  end

  # def chart
  # data_table = GoogleVisualr::DataTable.new
  # data_table.new_column('string', 'Event Type')
  # data_table.new_column('string', 'URL')
  # data_table.new_column('string', 'Date')
  # #I want to show page views per day
  # data_table.add_rows(#)
  #   #data_table.set_cell(0, 0, '2004')
    # use JSON to parse(events) ???

  #   opts   = { :width => 400, :height => 240, :title => 'Daily Page Views', :hAxis => { :title => 'Date' } }
  #   @chart = GoogleVisualr::Interactive::ColumnChart.new(data_table, opts)

  # end
  
  private

  def event_params
    params.require(:event).permit(:tracked_domain_id, :event_type, :url, :ip_address, :created_at, :updated_at) 
  end

end
 

app/controllers/events_controller.rb
class EventsController < ApplicationController
  respond_to :html, :js

  attr_accessor :tracked_domain_id
  
  before_action :find_tracked_domain
  
  def index
    @events = @tracked_domain.events.recent
  end

  def show
    @event = @tracked_domain.events.find(params[:id])
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    if @event.save
      flash[:notice] = "Event created successfully."
      redirect_to(:action => 'index')
    else
      render :new
    end
  end

  def edit
    @event = @tracked_domain.events.find(params[:id])
  end

  def update
    @event = @tracked_domain.events.find(params[:id])
    if @event.update_attributes(event_params)
      flash[:notice] = "Event updated successfully."
      redirect_to(:action => 'index')
    else
      render :edit
    end
  end

  def delete
    @event = @tracked_domain.events.find(params[:id])
  end

  def destroy
    @event = @tracked_domain.events.find(params[:id]).destroy
    flash[:notice] = "Event deleted successfully."
    redirect_to(:action => 'index')
  end

  private

  def event_params
    params.require(:event).permit(:tracked_domain_id, :event_type, :url, :ip_address, :created_at, :updated_at) 
  end

  def find_tracked_domain
    if params[:tracked_domain_id]
      @tracked_domain = current_user.tracked_domains.find(params[:tracked_domain_id])  
    end
  end
end

app/helpers/api/v1/events_helper.rb
module Api::V1::EventsHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/views/events/_form.html.haml
= form_for tracked_domain_events_path(tracked_domain), class: 'form-horizontal', remote: true do |f|
  .form-group
  = f.label(:tracked_domain_id, "Tracked Domain") 
  = f.select(:tracked_domain_id, @tracked_domains.map {|t| [t.name, t.id]})
  .form-group
  = f.label :event_type
  = f.radio_button(:event_type, 'Page View') 
  Page View
  = f.radio_button(:event_type, 'Click') 
  Click
  .form-group
  =f.label :url
  =f.url_field :url, class: 'form-control'
  .form-group
  = f.label :ip_address
  = f.text_field :ip_address, class: 'form-control'
  .form-group
  =f.submit "Save", class: 'btn btn-success btn-sm'

  

app/views/events/delete.html.haml
%h1 Event#delete
%p Find me in app/views/event/delete.html.haml

app/views/events/edit.html.haml
%h3 Edit Event
.row
  .col-md-4
    .col-md-8
= render partial: 'form', locals: { event: @event} 

app/views/events/index.html.haml
- @page_title ="Events"
.container
  %h1 Events
  %table.table.table-bordered.table-hover
    %tr
      %th Event ID
      %th Event Type
      %th URL
      %th IP Address
      %th Actions
      - @events.each do |event|
        %tr
          %td= event.id
          %td= event.event_type
          %td= event.url
          %td= event.ip_address
          %td
            = link_to 'Show Event', {:action => 'show', :id => event.id, :tracked_domain_id => @tracked_domain.id }
            |
            = link_to 'Edit', {:action => 'edit', :id => event.id, :tracked_domain_id => @tracked_domain.id }
            |
            = link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure you want to delete this event?' }



  = link_to "Add New Event", {:action => 'new', :tracked_domain_id => @tracked_domain.id }, class: 'btn btn-success'
  = link_to "Back to Tracked Domain", {:controller => 'tracked_domains', :action => 'show', :tracked_domain_id => @tracked_domain.id }, class: 'btn btn-success'

app/views/events/new.html.haml
%h3 Add an Event
.row
  .col-md-4
    .col-md-8
= render partial: 'form', locals: { tracked_domain: @tracked_domain } 

app/views/events/show.html.haml
.container
  %h3.col.md-6= @event
  %p= @event.event_type
  %p= @event.url
  %p= @event.ip_address

  %br
  = link_to 'New Event', new_tracked_domain_event_path, class: 'btn btn-primary btn-sm'
  = link_to "Edit Event", {:action => 'edit', :id => @event.id, :tracked_domain_id => @tracked_domain.id }, class: 'btn btn-success btn-sm'
  = link_to "Delete Event", {:action => 'delete', :id => @event.id, :tracked_domain_id => @tracked_domain.id }, class: 'btn btn-danger btn-sm', data: {confirm: 'Are you sure you want to delete this event?'}
  = link_to 'Back', tracked_domain_path(@wiki), class: 'btn btn-info btn-sm