config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :tracked_domains do
    resources :events
  end
  
  resources :verifications, only: [:update]

  namespace :api do
    namespace :v1 do
      resources :events, only: [:create, :index]
      match 'events.json' => "events#create", via: :options, as: :events_options
    end
  end

  #options 'api/v1/events.json' => "api/v1/events#index"
  match 'api/v1/events.json' => "api/v1/events#index", via: :options
  get 'get_started' => 'welcome#get_started', path: 'get_started'

  root 'welcome#index' 

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Blocmetrics
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "https://js.stripe.com/v1/", "https://www.google.com/jsapi", "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    .container
      .navbar.navbar-default.navbar-fixed-top 
        .navbar-header
          %button.navbar-toggle{type: "button", "data-toggle" => "collapse", "data-target" => ".navbar-collapse"}
            %span.sr-only
              | Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          .collapse.navbar-collapse
            %ul.nav.navbar-nav
              %li= link_to "Get Started", get_started_path
              %li= link_to "Tracked Domains", tracked_domains_path
              %li= link_to "Dashboard", api_v1_events_options_path
        .pull-right.user-info
          - if current_user
            Hello #{current_user.email}! #{link_to "Sign out", destroy_user_session_path, method: :delete}
          - else
            = link_to "Sign in", new_user_session_path
            or
            \#{link_to "Sign up", new_user_registration_path}

        - if flash[:notice]
          .alert.alert-success
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = flash[:notice]
        - elsif flash[:error]
          .alert.alert-danger
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = flash[:error]
        - elsif flash[:alert]
          .alert.alert-warning
            %button.close{"data-dismiss" => "alert", :type => "button"} ×
            = flash[:alert]
    = yield
    %footer © Blocmetrics   